window:
  startup_mode: "Maximized"

scrolling:
  history: 100000

font:
  normal:
    family: "HackGen Console for Powerline"
    style: "Regular"
  bold:
    family: "HackGen Console for Powerline"
    style: "Bold"

mouse:
  url:
    modifiers: "Command"

selection:
  save_to_clipboard: true


