window:
  startup_mode: "Maximized"

scrolling:
  history: 100000

font:
  normal:
    family: "HackGen Console for Powerline"
    style: "Regular"
  bold:
    family: "HackGen Console for Powerline"
    style: "Bold"

mouse:
  url:
    modifiers: "Command"

selection:
  save_to_clipboard: true

key_bindings:
  - { key: Key0,      mods: Command,         action: ResetFontSize    }
  - { key: Minus,     mods: Command,         action: DecreaseFontSize }
  - { key: Equals,    mods: Command,         action: IncreaseFontSize } # デフォ設定のハズだが効いてない模様
  - { key: Minus,     mods: Command|Shift,   action: IncreaseFontSize } # Equal が効かないようなので新規作成
  - { key: Add,       mods: Command,          action: IncreaseFontSize } # デフォ設定のハズだが効いてない模様
  - { key: Semicolon, mods: Command|Shift,   action: IncreaseFontSize } # Plus が効かないようなので新規作成
