window:
  startup_mode: "Maximized"

scrolling:
  history: 100000

font:
  normal:
    family: "HackGen35 Console"
    style: "Regular"
  bold:
    family: "HackGen35 Console"
    style: "Bold"

mouse:
  url:
    modifiers: "Command"

selection:
  save_to_clipboard: true

key_bindings:
  # Plus/Minux で拡大縮小、0 で本のサイズに戻す
  - { key: Key0,      mods: Command,         action: ResetFontSize    }
  - { key: Minus,     mods: Command,         action: DecreaseFontSize } # デフォ設定だが明記しておく
  - { key: Equals,    mods: Command,         action: IncreaseFontSize }
  - { key: Minus,     mods: Command|Shift,   action: IncreaseFontSize }
  - { key: Plus,      mods: Command,         action: IncreaseFontSize } # デフォ設定のハズだが効いてない模様
  - { key: Semicolon, mods: Command|Shift,   action: IncreaseFontSize } # Plus が効かないようなので追加
